window.PianoApp = window.PianoApp || {};

window.PianoApp.data = {
  projects: [
    {
      id: "1",
      name: "Nocturne Dashboard",
      description: "A real-time analytics platform for music streaming data.",
      year: "2025",
      category: "Web App",
      image: "assets/images/demo.jpg",
      tech: ["Next.js", "TypeScript", "D3.js"],
      link: "#",
    },
    {
      id: "2",
      name: "Symphony UI",
      description: "Design system and component library for enterprise products.",
      year: "2024",
      category: "Design System",
      image: "assets/images/demo.jpg",
      tech: ["React", "Tailwind", "Storybook"],
      link: "#",
    },
    {
      id: "3",
      name: "Resonance Audio",
      description: "Spatial audio engine for web-based immersive experiences.",
      year: "2024",
      category: "Audio Tool",
      image: "assets/images/demo.jpg",
      tech: ["Web Audio API", "Canvas", "WASM"],
      link: "#",
    },
    {
      id: "4",
      name: "Maestro Editor",
      description: "Collaborative score editing tool for composers.",
      year: "2023",
      category: "Creative Tool",
      image: "assets/images/demo.jpg",
      tech: ["Vue.js", "Firebase", "Tone.js"],
      link: "#",
    },
    {
      id: "5",
      name: "Aethelred Gallery",
      description: "Curated digital art gallery with generative curation.",
      year: "2023",
      category: "Art Platform",
      image: "assets/images/demo.jpg",
      tech: ["Next.js", "GraphQL", "Three.js"],
      link: "#",
    },
  ],

  experiences: [
    {
      id: "1",
      type: "work",
      orgName: "爱为舞科技有限公司",
      orgLabel: "独角兽",
      orgLocation: "北京",
      orgLogo: "",
      position: "产品经理",
      period: "2023 — Present",
      startDate: "2023-03",
      endDate: null,
      description: "负责 AI 驱动的舞蹈教学产品设计，从 0 到 1 搭建产品体系，主导与多所艺术院校的合作项目。",
      coords: { lon: 116.4074, lat: 39.9042 },
    },
    {
      id: "2",
      type: "work",
      orgName: "高露洁棕榄有限公司",
      orgLabel: "世界 500 强",
      orgLocation: "广州",
      orgLogo: "",
      position: "市场管培生",
      period: "2021 — 2023",
      startDate: "2021-07",
      endDate: "2023-06",
      description: "轮岗参与品牌管理、渠道运营和消费者洞察工作，协助完成年度营销预算制定与执行跟踪。",
      coords: { lon: 113.2644, lat: 23.1291 },
    },
    {
      id: "3",
      type: "study",
      orgName: "广州大学",
      orgLabel: "一本",
      orgLocation: "广州",
      orgLogo: "",
      position: "工商管理 · 本科",
      period: "2017 — 2021",
      startDate: "2017-09",
      endDate: "2021-06",
      description: "主修工商管理专业，GPA 3.8/4.0。担任学生会外联部部长，组织校级活动 10 余场。获得校级优秀毕业生称号。",
      coords: { lon: 113.3745, lat: 23.0403 },
    },
  ],

  skills: [
    "TypeScript",
    "React",
    "Next.js",
    "Node.js",
    "Tailwind CSS",
    "Web Audio",
    "Three.js",
    "PostgreSQL",
  ],

  socialLinks: [
    { name: "GitHub", url: "https://github.com" },
    { name: "LinkedIn", url: "https://linkedin.com" },
    { name: "Twitter", url: "https://twitter.com" },
  ],
};
